name: dart_swaymsg
description: A swaymsg clone written in dart.
version: 1.0.0
repository: https://github.com/AR-CADE/dart_swaymsg
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
dependencies:
  args: ^2.4.0
  i3_ipc:
    git:
      url: https://github.com/AR-CADE/i3_ipc.git
  on_exit: ^1.0.0
