name: dart_swaymsg
description: A swaymsg clone written in dart.
version: 2.1.0
repository: https://github.com/AR-CADE/dart_swaymsg
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  args: ^2.6.0
  bloc: ^9.0.0
  i3_ipc:
    git:
      url: https://github.com/AR-CADE/i3_ipc.git
  on_exit: ^1.0.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
