name: dart_swaymsg
description: A swaymsg clone written in dart.
version: 1.0.0
repository: https://github.com/AR-CADE/dart_swaymsg
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
dependencies:
  args: ^2.4.2
  i3_ipc:
    git:
      url: https://github.com/AR-CADE/i3_ipc.git
  on_exit: ^1.0.0
