name: dart_swaymsg
description: A swaymsg clone written in dart.
version: 2.0.1
repository: https://github.com/AR-CADE/dart_swaymsg
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
dependencies:
  args: ^2.4.2
  i3_ipc:
    git:
      url: https://github.com/AR-CADE/i3_ipc.git
  on_exit: ^1.0.0
  very_good_analysis: ^5.1.0
