name: dart_swaymsg
description: A swaymsg clone written in dart.
version: 2.0.8
repository: https://github.com/AR-CADE/dart_swaymsg
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  args: ^2.5.0
  bloc: ^8.1.4
  i3_ipc:
    git:
      url: https://github.com/AR-CADE/i3_ipc.git
  on_exit: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
